version: '3.2'

services:
  scraper-app-proxy:
    container_name: scraper-app-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - scraper-app
    ports:
      - '80:80'
      - '443:443'
    networks:
      - scraper-net
  scraper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - scraper-app-db
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
      - /usr/app/.next
    networks:
      - scraper-net
  scraper-app-db:
    image: mysql:8.0
    container_name: scraper-app-db
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraper-app
    networks:
      - scraper-net
    volumes:
      - scraper-app-db:/var/lib/mysql
volumes:
  scraper-app-db:
networks:
  scraper-net:
    driver: bridge
